# Software Name
TARGET = simplermenu_plus

CROSS_COMPILE = arm-linux-gnueabihf-

# Compiler
#CC = $(CROSS_COMPILE)g++
LINKER   = $(CROSS_COMPILE) g++
CFLAGS += -fdata-sections -ffunction-sections -fPIC -flto -Wall 
#-Ofast
LIBS += -lSDL -lSDL_image -lSDL_ttf -lSDL_gfx -lz -lpthread -lm -lboost_locale -lboost_filesystem -lasound

# You can use Ofast too but it can be more prone to bugs, careful.
CFLAGS += -MMD -MP -Iinclude/ -I$(SYSROOT)/usr/local/include/SDL -I$(SYSROOT)/usr/local/include -DPOWKIDDY=1
LDFLAGS += -Wl,--start-group $(LIBS) -Wl,--end-group -Wl,--as-needed -Wl,--gc-sections -flto

#DEBUG = YES

SRCDIR = src
OBJDIR = obj
BINDIR = output
SOURCES := $(wildcard $(SRCDIR)/*.cpp)

OBJECTS := $(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(SOURCES))
OBJECTS := $(patsubst $(SRCDIR)/%.c,$(OBJDIR)/%.o,$(OBJECTS))


rm = rm -f

all: $(BINDIR)/$(TARGET)

$(OBJDIR):
	mkdir -p $@

$(BINDIR):
	mkdir -p $@

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp | $(OBJDIR)
	$(CXX) $(CFLAGS) -c $< -o $@
	@echo "Compiled $< successfully!"

$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
	$(CXX) $(CFLAGS) -c $< -o $@
	@echo "Compiled $< successfully!"

$(BINDIR)/$(TARGET): $(OBJECTS) | $(BINDIR)
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
	@echo "Linking complete!"

-include $(OBJECTS:.o=.d)

.PHONY: clean
clean:
	$(rm) $(OBJECTS)
	@echo "Cleanup complete!"

.PHONY: remove
remove: clean
	$(rm) $(BINDIR)/$(TARGET)
	@echo "Executable removed!"

